name: text2video
channels:
    - pytorch
    - nvidia
    - defaults
    - anaconda
dependencies:
    - python=3.10
    - tqdm
    - nvidia/label/cuda-12.4.1::libnvjpeg
    - numpy<2.0.0
    - pytorch=2.5.1
    - torchvision>=0.20
    - torchtext
    - pytorch-cuda=12.4
    - tensorboard
    - chardet
    - pip
    - pyparsing
    - pip:
        - pillow-simd